### ISSUE TITLE
Does this repo only care CIS or more general?

### ISSUE THREAD

**Issue by fwang001** [hashicorp/terraform-foundational-policies-library#47]
Hi @hcrhall , I found this repo from the Terraform Cloud dashboard and before that, I have started a discussion at https://github.com/hashicorp/terraform-guides/issues/314

I can see there is a strong requirement to have a common/shared policy repo for people contributing. The terraform-guides repo doesn't fit that well, hence I asked if it's possible to have a dedicated repo for the policies. And then I found this one, but seems it only covers CIS, so my question is if we can have a joint collaboration to get both general policies and the CIS polices in the same repo and make it more easier to user to adopt.

Any comments will be appreciated. Thanks.

**Comment by hcrhall** [comment]
Hi @fwang001 

I think that this repository is a great place to start collaborating on common policies for Sentinel. While this repository contains policies that are based on the CIS benchmarks, there is nothing that prevents the Sentinel community from extending the library. It was always our hope that at some stage in the future we could allow the Sentinel community to contribute policies, policy sets, modules and plugins to this library.

I think that the first step would be to include a contribution guide to the repository so that folks have a clear understanding of how to contribute. Does this align with what you were thinking?

**Comment by fwang001** [comment]
Thank you for replying @hcrhall 

Totally. As I said in https://github.com/hashicorp/terraform-guides/issues/314 I can see Sentinel has the capability of a pluggable mechanism. So we just need an official place to host the policies and welcome the contribution from the wide community. It would nice if we can get more general/common policies, which will user's life much easier to apply those polices.

@rberlind can I please get you comments here? Thanks.
